/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * References to other objects. Must contain references for only: `attributes`, `home`, `links`, `root`, `self`.
 */
export interface InlineResponse2003Hrefs {
  /**
   * Relation to this object.
   */
  rel?: string;
  /**
   * URL to reference.
   */
  href?: string;
}
