/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ACLS } from './aCLS';

export interface InlineResponse201 {
  acls?: ACLS;
  /**
   * When domain was created.
   */
  created?: number;
  /**
   * When object was last modified.
   */
  lastModified?: number;
  /**
   * Name of owner.
   */
  owner?: string;
  /**
   * ID of root group.
   */
  root?: string;
}
