/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse2007TypeFields { 
    /**
     * Descriptive or identifying name. Must be unique in the fields list. 
     */
    name?: string;
    /**
     * Enum of pre-defined type, UUID of committed type, or type definition. (TODO: see `POST Dataset`?) 
     */
    type?: string;
}

