/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2008Hrefs } from './inlineResponse2008Hrefs';
import { ACLS } from './aCLS';

/**
 * TODO
 */
export interface InlineResponse20016 {
  acls?: ACLS;
  hrefs?: Array<InlineResponse2008Hrefs>;
}
