import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterTestingModule } from '@angular/router/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import {
  FontAwesomeModule,
  FaIconLibrary,
} from '@fortawesome/angular-fontawesome';
import {
  faFileAlt,
  faFileCode,
  faCircle,
  faCalendarAlt,
  faClock,
  faSquare,
  faPlusSquare,
  faMinusSquare,
  faComment,
  faEye,
} from '@fortawesome/free-regular-svg-icons';
import {
  faProjectDiagram,
  faCog,
  faCogs,
  faChartArea,
  faSignInAlt,
  faSignOutAlt,
  faUser,
  faUsers,
  faUserPlus,
  faHourglassHalf,
  faLink,
  faEnvelope,
  faDna,
  faTag,
  faTags,
  faInfo,
  faQuestion,
  faFlask,
  faHistory,
  faUnlockAlt,
  faTerminal,
  faList,
  faStopwatch,
  faSitemap,
  faKey,
  faClone,
  faCertificate,
  faCircle as FaSolidCircle,
  faAlignJustify,
  faPencilAlt,
  faCalculator,
  faStar,
  faDownload,
  faCodeBranch,
  faPlus,
  faTrashAlt,
  faBars,
  faQuestionCircle,
  faInfoCircle,
  faUserCircle,
  faPlusCircle,
  faGripLinesVertical,
  faFolderOpen,
  faChartBar,
  faChartPie,
  faTable,
  faThList,
  faThLarge,
  faBug,
  faTools,
  faMap,
  faPaintBrush,
  faTasks,
  faDatabase,
  faHardHat,
} from '@fortawesome/free-solid-svg-icons';
import {
  faDocker,
  faGithub,
  faGoogle,
  faOrcid,
  faOsi,
} from '@fortawesome/free-brands-svg-icons';
import { MaterialModule } from '../app-material.module';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
const modules = [
  RouterTestingModule,
  HttpClientTestingModule,
  FormsModule,
  MaterialModule,
  ReactiveFormsModule,
  NoopAnimationsModule,
  FontAwesomeModule,
];

@NgModule({
  declarations: [],
  imports: [CommonModule, ...modules],
  exports: [...modules],
})
export class BiosimulationsFrontendTestingModule {
  constructor(library: FaIconLibrary) {
    library.addIcons(
      faFileAlt,
      faFileCode,
      faCircle,
      faCalendarAlt,
      faClock,
      faSquare,
      faPlusSquare,
      faMinusSquare,
      faComment,
      faEye,
      faSignInAlt,
      faSignOutAlt,
      faUser,
      faUsers,
      faUserPlus,
      faProjectDiagram,
      faCog,
      faCogs,
      faChartArea,
      faHourglassHalf,
      faLink,
      faEnvelope,
      faDna,
      faTag,
      faTags,
      faInfo,
      faQuestion,
      faFlask,
      faHistory,
      faUnlockAlt,
      faTerminal,
      faList,
      faStopwatch,
      faSitemap,
      faKey,
      faClone,
      faCertificate,
      FaSolidCircle,
      faAlignJustify,
      faPencilAlt,
      faCalculator,
      faStar,
      faDownload,
      faCodeBranch,
      faPlus,
      faTrashAlt,
      faBars,
      faQuestionCircle,
      faInfoCircle,
      faUserCircle,
      faPlusCircle,
      faGripLinesVertical,
      faFolderOpen,
      faChartBar,
      faChartPie,
      faTable,
      faThList,
      faThLarge,
      faBug,
      faTools,
      faMap,
      faPaintBrush,
      faTasks,
      faDatabase,
      faDocker,
      faGithub,
      faGoogle,
      faOrcid,
      faOsi,
      faHardHat,
    );
  }
}
