/**
 * BioSimulations COMBINE API
 * Endpoints for working with models (e.g., [CellML](https://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](https://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CombineArchive } from './combineArchive';
import { FilenameOrUrl } from './filenameOrUrl';

/**
 * COMBINE/OMEX archive and (a) modified specifications for its SED-ML documents and/or (b) modified versions of its files.
 */
export interface ModifyCombineArchiveSpecsAndFiles {
  specs: CombineArchive;
  /**
   * File (e.g., model) to place into the COMBINE/OMEX archive.
   */
  files?: Array<Blob>;
  /**
   * Whether to download the modified archive or return a URL where the modified archive can be downloaded.
   */
  download?: boolean;
  archive: FilenameOrUrl;
}
