/**
 * BioSimulations COMBINE API
 * Endpoints for working with models (e.g., [CellML](https://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](https://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Graphical style of a line
 */
export interface SedLineStyle {
  /**
   * Type
   */
  _type: SedLineStyleTypeEnum;
  /**
   * Type
   */
  type?: SedLineStyleTypeEnum;
  /**
   * A 6 or 8-digit case-insensitive hexidecimal color
   */
  color?: string;
  /**
   * Thickness or width
   */
  thickness?: number;
}
export enum SedLineStyleTypeEnum {
  SedLineStyle = 'SedLineStyle',
}
export enum SedLineStyleTypeEnum {
  none = 'none',
  solid = 'solid',
  dash = 'dash',
  dot = 'dot',
  dashDot = 'dashDot',
  dashDotDot = 'dashDotDot',
}
