/**
 * BioSimulations COMBINE API
 * Endpoints for working with models (e.g., [CellML](https://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](https://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SedTarget } from './sedTarget';

/**
 * A SED variable.
 */
export interface SedVariable {
  /**
   * Unique identifier within its parent SED document.
   */
  id: string;
  /**
   * Brief description.
   */
  name?: string;
  /**
   * Task.
   */
  task: string;
  target?: SedTarget;
  /**
   * Symbol (e.g., for an implicit variable that is not explicitly defined in the specification of a model, such as time).
   */
  symbol?: string;
  /**
   * Type.
   */
  _type: SedVariableTypeEnum;
  /**
   * Identifier of the model from which the variable should be recorded
   */
  model?: string;
}
export enum SedVariableTypeEnum {
  SedVariable = 'SedVariable',
}
