/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CombineArchive } from './combineArchive';


/**
 * Specifications of a COMBINE/OMEX archive (including its SED-ML files) and the other (non-SED-ML) files that it should contain.
 */
export interface CombineArchiveSpecsAndFiles { 
    specs: CombineArchive;
    /**
     * File (e.g., model) to place into the COMBINE/OMEX archive.
     */
    files?: Array<Blob>;
    /**
     * Whether to download the archive or return a URL where the archive can be downloaded.
     */
    download?: boolean;
}

