/**
 * BioSimulations COMBINE service
 * Endpoints for working with models (e.g., [CellML](http://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](http://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CombineArchive } from './combineArchive';

/**
 * Specifications of a COMBINE/OMEX archive (including its SED-ML files) and the other (non-SED-ML) files that it should contain.
 */
export interface CombineArchiveSpecsAndFiles {
  specs: CombineArchive;
  /**
   * File (e.g., model) to place into the COMBINE/OMEX archive.
   */
  files?: Array<Blob>;
  /**
   * Whether to download the archive or return a URL where the archive can be downloaded.
   */
  download?: boolean;
}
