/**
 * BioSimulations COMBINE service
 * Endpoints for working with models (e.g., [CellML](http://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](http://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A value of an environment variable
 */
export interface EnvironmentVariable {
  /**
   * Type
   */
  _type: EnvironmentVariableType;
  /**
   * Name of the environment variable
   */
  key: string;
  /**
   * Value of the environment variable
   */
  value: string;
}
export enum EnvironmentVariableType {
  EnvironmentVariable = 'EnvironmentVariable',
}
