/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * File or a URL for getting the information in an [OMEX Metadata](https://sys-bio.github.io/libOmexMeta/) document
 */
export interface GetCombineArchiveMetadataFileOrUrl {
  /**
   * The two files uploaded in creating a combine archive
   */
  file?: Blob;
  /**
   * URL
   */
  url?: string;
  /**
   * OMEX Metadata format  Default: `rdfxml`
   */
  omexMetadataFormat: GetCombineArchiveMetadataFileOrUrlOmexMetadataFormat;
}
export enum GetCombineArchiveMetadataFileOrUrlOmexMetadataFormat {
  Ntriples = 'ntriples',
  Nquads = 'nquads',
  Rdfa = 'rdfa',
  Rdfxml = 'rdfxml',
  Turtle = 'turtle',
}
