/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Algorithm substitution policy, the degree to switch algorithms can be substituted for each other.
 */
export interface KisaoAlgorithmSubstitutionPolicy {
  /**
   * Id of the policy
   */
  id: KisaoAlgorithmSubstitutionPolicy.IdEnum;
  /**
   * Level of the policy (0: most restrictive to 9: least restrictive)
   */
  level: number;
  /**
   * Name of the policy
   */
  name: KisaoAlgorithmSubstitutionPolicy.NameEnum;
  /**
   * Type
   */
  _type: KisaoAlgorithmSubstitutionPolicy.TypeEnum;
}
export namespace KisaoAlgorithmSubstitutionPolicy {
  export type IdEnum =
    | 'NONE'
    | 'SAME_METHOD'
    | 'SAME_MATH'
    | 'SIMILAR_APPROXIMATIONS'
    | 'DISTINCT_APPROXIMATIONS'
    | 'DISTINCT_SCALES'
    | 'SAME_VARIABLES'
    | 'SIMILAR_VARIABLES'
    | 'SAME_FRAMEWORK'
    | 'ANY';
  export const IdEnum = {
    None: 'NONE' as IdEnum,
    SameMethod: 'SAME_METHOD' as IdEnum,
    SameMath: 'SAME_MATH' as IdEnum,
    SimilarApproximations: 'SIMILAR_APPROXIMATIONS' as IdEnum,
    DistinctApproximations: 'DISTINCT_APPROXIMATIONS' as IdEnum,
    DistinctScales: 'DISTINCT_SCALES' as IdEnum,
    SameVariables: 'SAME_VARIABLES' as IdEnum,
    SimilarVariables: 'SIMILAR_VARIABLES' as IdEnum,
    SameFramework: 'SAME_FRAMEWORK' as IdEnum,
    Any: 'ANY' as IdEnum,
  };
  export type NameEnum =
    | 'None'
    | 'Same method'
    | 'Same math'
    | 'Similar approximations'
    | 'Distinct approximations'
    | 'Distinct scales'
    | 'Same variables'
    | 'Similar variables'
    | 'Same framework'
    | 'Any';
  export const NameEnum = {
    None: 'None' as NameEnum,
    SameMethod: 'Same method' as NameEnum,
    SameMath: 'Same math' as NameEnum,
    SimilarApproximations: 'Similar approximations' as NameEnum,
    DistinctApproximations: 'Distinct approximations' as NameEnum,
    DistinctScales: 'Distinct scales' as NameEnum,
    SameVariables: 'Same variables' as NameEnum,
    SimilarVariables: 'Similar variables' as NameEnum,
    SameFramework: 'Same framework' as NameEnum,
    Any: 'Any' as NameEnum,
  };
  export type TypeEnum = 'KisaoAlgorithmSubstitutionPolicy';
  export const TypeEnum = {
    KisaoAlgorithmSubstitutionPolicy:
      'KisaoAlgorithmSubstitutionPolicy' as TypeEnum,
  };
}
