/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SedDataGenerator } from './sedDataGenerator';

/**
 * Curve of a 2D SED plot
 */
export interface SedCurve {
  /**
   * Unique identifier with its parent SED document.
   */
  id: string;
  /**
   * Brief description.
   */
  name?: string;
  xDataGenerator: SedDataGenerator;
  yDataGenerator: SedDataGenerator;
  /**
   * Type.
   */
  _type: SedCurve.TypeEnum;
}
export namespace SedCurve {
  export type TypeEnum = 'SedCurve';
  export const TypeEnum = {
    SedCurve: 'SedCurve' as TypeEnum,
  };
}
