/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SedDataGenerator } from './sedDataGenerator';

/**
 * A SED data set
 */
export interface SedDataSet {
  /**
   * Unique identifier within its parent SED document.
   */
  id: string;
  /**
   * Brief description
   */
  label: string;
  /**
   * Brief description.
   */
  name?: string;
  dataGenerator: SedDataGenerator;
  /**
   * Type.
   */
  _type: SedDataSetType;
}
export enum SedDataSetType {
  SedDataSet = 'SedDataSet',
}
