/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulatorApi } from './simulatorApi';


/**
 * Simulation tool
 */
export interface Simulator { 
    /**
     * Type
     */
    _type: SimulatorType;
    /**
     * Id of a simulation tool registered with BioSimulators.
     */
    id: string;
    /**
     * Version of the simulation tool
     */
    version: string;
    /**
     * URL
     */
    specs: string;
    api: SimulatorApi;
    /**
     * Name
     */
    name: string;
}
export enum SimulatorType {
    Simulator = 'Simulator'
};



