/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Environment } from './environment';


/**
 * Request for the execution of a COMBINE/OMEX archive
 */
export interface SimulationRun { 
    /**
     * Id of a simulation tool registered with BioSimulators.
     */
    simulator: string;
    /**
     * URL
     */
    archiveUrl?: string;
    /**
     * The two files uploaded in creating a combine archive
     */
    archiveFile?: Blob;
    /**
     * Type
     */
    _type: SimulationRunType;
    environment?: Environment;
}
export enum SimulationRunType {
    SimulationRun = 'SimulationRun'
};



