/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * File or a URL for validating a model.
 */
export interface ValidateModelFileOrUrl { 
    /**
     * The two files uploaded in creating a combine archive
     */
    file?: Blob;
    /**
     * URL
     */
    url?: string;
    /**
     * Language of the model
     */
    language: ValidateModelFileOrUrlLanguage;
}
export enum ValidateModelFileOrUrlLanguage {
    Bngl = 'BNGL',
    CellMl = 'CellML',
    Lems = 'LEMS',
    NeuroMl = 'NeuroML',
    Rba = 'RBA',
    Sbml = 'SBML',
    Smoldyn = 'Smoldyn',
    Xpp = 'XPP'
};



