/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Error or warning message about validity (e.g., of a COMBINE/OMEX archive).
 */
export interface ValidationMessage {
  /**
   * Child messages with more detailed information.
   */
  details?: Array<ValidationMessage>;
  /**
   * Type.
   */
  _type: ValidationMessageType;
  /**
   * Information about validity or lack thereof.
   */
  summary: string;
}
export enum ValidationMessageType {
  ValidationMessage = 'ValidationMessage',
}
