/**
 * BioSimulations COMBINE service
 * Endpoints for working with COMBINE/OMEX archives and model (e.g., SBML) and simulation (e.g., SED-ML) files that they typically contain.  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMessage } from './validationMessage';

/**
 * Information about whether a COMBINE archive is valid, potentially invalid (1 or more warnings), or invalid (1 or more errors).
 */
export interface ValidationReport {
  /**
   * Errors with the archive.
   */
  errors?: Array<ValidationMessage>;
  /**
   * Overall status of the archive.
   */
  status: ValidationReport.StatusEnum;
  /**
   * Warnings for the archive.
   */
  warnings?: Array<ValidationMessage>;
  /**
   * Type
   */
  _type: ValidationReport.TypeEnum;
}
export namespace ValidationReport {
  export type StatusEnum = 'valid' | 'invalid' | 'warnings';
  export const StatusEnum = {
    Valid: 'valid' as StatusEnum,
    Invalid: 'invalid' as StatusEnum,
    Warnings: 'warnings' as StatusEnum,
  };
  export type TypeEnum = 'ValidationReport';
  export const TypeEnum = {
    ValidationReport: 'ValidationReport' as TypeEnum,
  };
}
