export const environment = {
  production: false,
  baseUrl: '/',
  auth0: {
    domain: 'crbm.auth0.com',
    audience: 'api.biosimulations.org',
    clientId: '0NKMjbZuexkCgfWY3BG9C3808YsdLUrb',
  },
  crbm: {
    CRBMAPI_URL: 'https://crbm-api.herokuapp.com',
    ALLOWED_FILE_EXTENSIONS: [
      'pdf',
      'doc',
      'ppt',
      'txt',
      'xlsx',
      'sedx',
      'sbex',
      'cmex',
      'sbox',
      'neux',
      'phex',
      'zip',
      'jpg',
      'png',
      'jpeg',
      'raw',
      'sh',
    ],
  },
};
