declare module 'stackdriver-errors-js';
declare module 'highlight.js/lib/languages/dockerfile';
declare module 'highlight.js/lib/languages/json';
declare module 'highlight.js/lib/languages/typescript';
declare module 'highlight.js/lib/languages/xml';
declare module 'highlight.js/lib/languages/yaml';
declare module 'highlight.js/lib/core';
declare module '@openapi-contrib/openapi-schema-to-json-schema';
declare module 'ansi-to-html';
