export interface ModelFormat {
  name: string;
  acronym: string | null;
  edamId: string;
  sedUrn: string;
  combineUri: string;
  mediaTypes: string[];
  extensions: string[];
  enabled: boolean;
}

export const MODEL_FORMATS: ModelFormat[] = [
  {
    name: 'BNGL',
    acronym: 'BNGL',
    edamId: 'format_3972',
    sedUrn: 'urn:sedml:language:bngl',
    combineUri: 'http://purl.org/NET/mediatypes/text/bngl+plain',
    mediaTypes: [
      'text/bngl+plain',
      'text/plain',
      'text/x-bngl',
      'application/x-bngl',
    ],
    extensions: ['bngl'],
    enabled: true,
  },
  {
    name: 'CellML',
    acronym: null,
    edamId: 'format_3240',
    sedUrn: 'urn:sedml:language:cellml',
    combineUri: 'http://identifiers.org/combine.specifications/cellml',
    mediaTypes: [
      'application/cellml+xml',
      'application/x-cellml',
      'application/xml',
    ],
    extensions: ['cellml', 'xml'],
    enabled: true,
  },
  {
    name: 'COPASI Markup Language',
    acronym: 'CopasiML',
    edamId: 'format_9003',
    sedUrn: 'urn:sedml:language:copasiml',
    combineUri: 'http://purl.org/NET/mediatypes/application/x-copasi',
    mediaTypes: [
      'application/x-copasi',
      'application/copasiml+xml',
      'application/xml',
    ],
    extensions: ['cps'],
    enabled: false,
  },
  {
    name: 'GINsim Markup Language',
    acronym: 'GINML',
    edamId: 'format_9009',
    sedUrn: 'urn:sedml:language:ginml',
    combineUri: 'http://purl.org/NET/mediatypes/application/ginml+xml',
    mediaTypes: ['application/ginml+xml', 'application/xml'],
    extensions: ['ginml'],
    enabled: false,
  },
  {
    name: 'High Order Calculator',
    acronym: 'HOC',
    edamId: 'format_9005',
    sedUrn: 'urn:sedml:language:hoc',
    combineUri: 'http://purl.org/NET/mediatypes/text/x-hoc',
    mediaTypes: ['text/x-hoc', 'text/plain'],
    extensions: ['hoc'],
    enabled: false,
  },
  {
    name: 'Kappa',
    acronym: null,
    edamId: 'format_9006',
    sedUrn: 'urn:sedml:language:kappa',
    combineUri: 'http://purl.org/NET/mediatypes/text/x-kappa',
    mediaTypes: ['text/x-kappa', 'text/plain'],
    extensions: ['ka'],
    enabled: true,
  },
  {
    name: 'Low Entropy Model Specification',
    acronym: 'LEMS',
    edamId: 'format_9004',
    sedUrn: 'urn:sedml:language:lems',
    combineUri: 'http://purl.org/NET/mediatypes/application/lems+xml',
    mediaTypes: [
      'application/lems+xml',
      'application/x-lems',
      'application/xml',
    ],
    extensions: ['xml'],
    enabled: true,
  },
  {
    name: 'Mass Action Stoichiometric Simulation',
    acronym: 'MASS',
    edamId: 'format_9011',
    sedUrn: 'urn:sedml:language:mass',
    combineUri: 'http://purl.org/NET/mediatypes/application/mass+json',
    mediaTypes: ['application/mass+json', 'application/json'],
    extensions: ['json'],
    enabled: false,
  },
  {
    name: 'Morpheus Markup Language',
    acronym: 'MorpheusML',
    edamId: 'format_9002',
    sedUrn: 'urn:sedml:language:morpheusml',
    combineUri: 'http://purl.org/NET/mediatypes/application/morpheusml+xml',
    mediaTypes: ['application/morpheusml+xml', 'application/xml'],
    extensions: ['xml'],
    enabled: false,
  },
  {
    name: 'NeuroML',
    acronym: null,
    edamId: 'format_3971',
    sedUrn: 'urn:sedml:language:neuroml',
    combineUri: 'http://identifiers.org/combine.specifications/neuroml',
    mediaTypes: ['application/neuroml+xml', 'application/xml'],
    extensions: ['nml'],
    enabled: false,
  },
  {
    name: 'Pharmacometrics Markup Language ',
    acronym: 'pharmML',
    edamId: 'format_9007',
    sedUrn: 'urn:sedml:language:pharmml',
    combineUri: 'http://purl.org/NET/mediatypes/application/pharmml+xml',
    mediaTypes: ['application/pharmml+xml', 'application/xml'],
    extensions: ['xml'],
    enabled: true,
  },
  {
    name: 'RBA models',
    acronym: null,
    edamId: 'format_9012',
    sedUrn: 'urn:sedml:language:rba',
    combineUri: 'http://purl.org/NET/mediatypes/application/rba+zip',
    mediaTypes: ['application/rba+zip', 'application/zip'],
    extensions: ['zip'],
    enabled: false,
  },
  {
    name: 'Systems Biology Markup Language',
    acronym: 'SBML',
    edamId: 'format_2585',
    sedUrn: 'urn:sedml:language:sbml',
    combineUri: 'http://identifiers.org/combine.specifications/sbml',
    mediaTypes: [
      'application/sbml+xml',
      'application/x-sbml',
      'application/xml',
    ],
    extensions: ['xml', 'sbml'],
    enabled: true,
  },
  {
    name: 'Smoldyn',
    acronym: null,
    edamId: 'format_9001',
    sedUrn: 'urn:sedml:language:smoldyn',
    combineUri: 'http://purl.org/NET/mediatypes/text/smoldyn+plain',
    mediaTypes: [
      'text/smoldyn+plain',
      'text/plain',
      'text/x-smoldyn',
      'application/x-smoldyn',
    ],
    extensions: ['txt'],
    enabled: true,
  },
  {
    name: 'Virtual Cell Markup Language',
    acronym: 'VCML',
    edamId: 'format_9000',
    sedUrn: 'urn:sedml:language:vcml',
    combineUri: 'http://purl.org/NET/mediatypes/application/vcml+xml',
    mediaTypes: ['application/vcml+xml', 'application/xml'],
    extensions: ['vcml'],
    enabled: false,
  },
  {
    name: 'XPP',
    acronym: null,
    edamId: 'format_9010',
    sedUrn: 'urn:sedml:language:xpp',
    combineUri: 'http://purl.org/NET/mediatypes/text/x-xpp',
    mediaTypes: [
      'text/x-xpp',
      'text/plain',
      'text/xpp+plain',
      'application/x-xpp',
    ],
    extensions: ['ode', 'xpp'],
    enabled: true,
  },
  {
    name: 'GINsim Markup Language, Zipped',
    acronym: 'ZGINML',
    edamId: 'format_9008',
    sedUrn: 'urn:sedml:language:zginml',
    combineUri: 'http://purl.org/NET/mediatypes/application/zginml+zip',
    mediaTypes: [
      'application/zginml+zip',
      'application/x-zginml',
      'application/zip',
    ],
    extensions: ['zginml', 'zip'],
    enabled: true,
  },
];

export const SEDML_FORMAT = {
  name: 'Simulation Experiment Description Markup Language',
  acronym: 'SED-ML',
  edamId: 'format_3685',
  combineUri: 'http://identifiers.org/combine.specifications/sed-ml',
  mediaTypes: ['application/sedml+xml', 'application/xml'],
  extensions: ['sedml'],
};
