/**
 * BioSimulations COMBINE API
 * Endpoints for working with models (e.g., [CellML](https://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](https://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SedOutputElementLog } from './sedOutputElementLog';
import { SedPlot2DLog } from './sedPlot2DLog';
import { SedPlot3DLog } from './sedPlot3DLog';
import { SedReportLog } from './sedReportLog';
import { Exception } from './exception';

/**
 * @type SedDocumentLogOutputsInner
 * @export
 */
export type SedDocumentLogOutputsInner = SedPlot2DLog | SedPlot3DLog | SedReportLog;
