/**
 * BioSimulations COMBINE API
 * Endpoints for working with models (e.g., [CellML](https://cellml.org/), [SBML](http://sbml.org/)), simulation experiments (e.g., [Simulation Experiment Description Language (SED-ML)](https://sed-ml.org/)), metadata ([OMEX Metadata](https://sys-bio.github.io/libOmexMeta/)), and simulation projects ([COMBINE/OMEX archives](https://combinearchive.org/)).  Note, this API may change significantly in the future.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SedAddElementModelChange } from './sedAddElementModelChange';
import { SedReplaceElementModelChange } from './sedReplaceElementModelChange';
import { SedParameter } from './sedParameter';
import { SedVariable } from './sedVariable';
import { SedComputeModelChange } from './sedComputeModelChange';
import { SedRemoveElementModelChange } from './sedRemoveElementModelChange';
import { SedTarget } from './sedTarget';
import { SedModelAttributeChange } from './sedModelAttributeChange';

/**
 * A SED model change.
 */
/**
 * @type SedModelChange
 * A SED model change.
 * @export
 */
export type SedModelChange =
  | SedAddElementModelChange
  | SedComputeModelChange
  | SedModelAttributeChange
  | SedRemoveElementModelChange
  | SedReplaceElementModelChange;
