import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { SharedUiModule } from '@biosimulations/shared/ui';
import { moduleMetadata, Story, Meta } from '@storybook/angular';
import { GridModule } from '../../grid.module';
import { AutoCompleteFilterComponent } from './auto-complete-filter.component';

export default {
  title: 'AutoCompleteFilterComponent',
  component: AutoCompleteFilterComponent,
  decorators: [
    moduleMetadata({
      imports: [GridModule, BrowserAnimationsModule, SharedUiModule],
    }),
  ],
  args: {
    header: 'Biology',
    values: [
      {
        id: '1',
        label: 'E. coli',
        selected: false,
      },
      {
        id: '2',
        label: 'H. sapiens',
        selected: true,
      },
      {
        id: '3',
        label: 'H. neanderthalensis',
        selected: true,
      },
    ],
  },
  argTypes: {
    autoCompleteFilterChange: {
      action: 'autoCompleteFilterChange',
    },
  },
} as Meta<AutoCompleteFilterComponent>;

const Template: Story<AutoCompleteFilterComponent> = (args: AutoCompleteFilterComponent) => ({
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {};

const columns = [
  {
    id: 'id',
    key: 'id',
    heading: 'Id',
    leftIcon: 'id',
    filterable: false,
    hidden: true,
    show: false,
    _index: 0,
    _visible: false,
  },
  {
    id: 'title',
    key: 'title',
    heading: 'Title',
    leftIcon: 'file',
    filterable: false,
    hidden: true,
    show: false,
    _index: 1,
    _visible: false,
  },
  {
    id: 'abstract',
    key: ['metadata', 'abstract'],
    heading: 'Abstract',
    leftIcon: 'file',
    filterable: false,
    hidden: false,
    show: true,
    _index: 2,
    _visible: true,
  },
  {
    id: 'description',
    key: ['metadata', 'description'],
    heading: 'Description',
    leftIcon: 'file',
    filterable: false,
    hidden: false,
    show: false,
    _index: 3,
    _visible: false,
  },
  {
    id: 'biology',
    key: ['metadata', 'encodes'],
    heading: 'Biology',
    leftIcon: 'cell',
    filterable: true,
    hidden: false,
    show: true,
    _index: 4,
    _visible: true,
    filterDefinition: {
      type: 'stringAutoComplete',
      value: [
        { label: 'anatomical structure morphogenesis', selected: false },
        { label: 'calcineurin-NFAT signaling cascade', selected: false },
        { label: 'cell cycle', selected: false },
        { label: 'cell surface receptor signaling pathway', selected: false },
        { label: 'Channel/Receptor', selected: false },
        { label: 'DEP Domain-Containing mTOR-Interacting Protein', selected: false },
        { label: 'epidermal growth factor receptor signaling pathway', selected: false },
        { label: 'Heart cell', selected: false },
        { label: 'Heart disease', selected: false },
        { label: 'HERG current', selected: false },
        { label: 'HERG KCNH2', selected: false },
        { label: 'I K', selected: false },
        { label: 'I_HERG', selected: false },
        { label: 'Ion Channel Kinetics', selected: false },
        { label: 'iron ion homeostasis', selected: false },
        { label: 'JURKAT cell', selected: false },
        { label: 'Long-QT', selected: false },
        { label: 'mitotic morphogenesis checkpoint signaling', selected: false },
        { label: 'mTOR signaling pathway', selected: false },
        { label: 'neuromuscular synaptic transmission', selected: false },
        { label: 'regulation of gene expression, epigenetic', selected: false },
        { label: 'signaling pathway', selected: false },
        { label: 'transmission of nerve impulse', selected: false },
        { label: 'tumor necrosis factor-mediated signaling pathway', selected: false },
      ],
    },
  },
  {
    id: 'taxa',
    key: ['metadata', 'taxa'],
    heading: 'Taxa',
    leftIcon: 'taxon',
    filterable: true,
    hidden: false,
    show: true,
    _index: 5,
    _visible: true,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'Escherichia coli', selected: false },
        { label: 'Escherichia coli K-12', selected: false },
        { label: 'Homo sapiens', selected: false },
        { label: 'Mus musculus', selected: false },
        { label: 'Rattus norvegicus', selected: false },
        { label: 'Saccharomyces cerevisiae', selected: false },
        { label: 'Schizosaccharomyces pombe', selected: false },
        { label: 'Tetronarce californica', selected: false },
      ],
    },
  },
  {
    id: 'keywords',
    key: ['metadata', 'keywords'],
    heading: 'Keywords',
    leftIcon: 'tag',
    filterable: true,
    hidden: false,
    show: false,
    _index: 6,
    _visible: false,
    filterDefinition: {
      type: 'stringAutoComplete',
      value: [
        { label: 'anemia', selected: false },
        { label: 'ATP-senstive potassium current', selected: false },
        { label: 'biological clock', selected: false },
        { label: 'Biological Clocks', selected: false },
        { label: 'Calcium Signaling', selected: false },
        { label: 'cell cycle', selected: false },
        { label: 'cell division', selected: false },
        { label: 'Cellular Senescence', selected: false },
        { label: 'Cricetinae', selected: false },
        { label: 'cyclin-dependent kinase', selected: false },
        { label: 'Cyclin-Dependent Kinase Inhibitor p21', selected: false },
        { label: 'DNA damage', selected: false },
        { label: 'DNA End-Joining Repair', selected: false },
        { label: 'erythrocyte', selected: false },
        { label: 'Heat shock proteins', selected: false },
        { label: 'Heat shock response', selected: false },
        { label: 'Hemochromatosis', selected: false },
        { label: 'Hepcidins', selected: false },
        { label: 'immunology', selected: false },
        { label: 'immunotherapy', selected: false },
        { label: 'Ion Channel Gating', selected: false },
        { label: 'IP3', selected: false },
        { label: 'iron', selected: false },
        { label: 'K channel', selected: false },
        { label: 'Kir6.2 KCNJ11', selected: false },
        { label: 'Membrane Potentials', selected: false },
        { label: 'metabolism', selected: false },
        { label: 'morphogenesis', selected: false },
        { label: 'neoplasm', selected: false },
        { label: 'NFATC Transcription Factors', selected: false },
        { label: 'oscillator', selected: false },
        { label: 'Pituitary cell', selected: false },
        { label: 'RBA', selected: false },
        { label: 'Receptors, Nicotinic', selected: false },
        { label: 'resource balance allocation', selected: false },
        { label: 'resource balance analysis', selected: false },
        { label: 'signal transduction', selected: false },
        { label: 'Signal Transduction', selected: false },
        { label: 'Synapses', selected: false },
        { label: 'synthetic biology', selected: false },
        { label: 'Tumor Suppressor Protein p53', selected: false },
      ],
    },
  },
  {
    id: 'citations',
    key: ['metadata', 'citations'],
    heading: 'Citations',
    leftIcon: 'journal',
    filterable: true,
    hidden: false,
    show: false,
    _index: 7,
    _visible: false,
    filterDefinition: { type: 'string', value: [{ label: 'Yes', selected: false }] },
  },
  {
    id: 'identifiers',
    key: ['metadata', 'identifiers'],
    heading: 'Identifiers',
    leftIcon: 'id',
    filterable: false,
    hidden: false,
    show: false,
    _index: 8,
    _visible: false,
  },
  {
    id: 'other',
    key: ['metadata', 'other'],
    heading: 'Additional metadata',
    leftIcon: 'info',
    filterable: false,
    hidden: false,
    show: false,
    _index: 9,
    _visible: false,
  },
  {
    id: 'modelFormats',
    key: 'tasks',
    heading: 'Model formats',
    leftIcon: 'format',
    hidden: false,
    show: false,
    filterable: true,
    _index: 10,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'BNGL', selected: false },
        { label: 'CellML', selected: false },
        { label: 'LEMS', selected: false },
        { label: 'RBA XML', selected: false },
        { label: 'SBML', selected: false },
        { label: 'Smoldyn', selected: false },
        { label: 'XPP', selected: false },
      ],
    },
  },
  {
    id: 'simulationTypes',
    key: 'tasks',
    heading: 'Simulation types',
    leftIcon: 'framework',
    hidden: false,
    show: false,
    filterable: true,
    _index: 11,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'Steady state', selected: false },
        { label: 'Uniform time course', selected: false },
      ],
    },
  },
  {
    id: 'simulationAlgorithms',
    key: 'tasks',
    heading: 'Simulation algorithms',
    leftIcon: 'framework',
    hidden: false,
    show: false,
    filterable: true,
    _index: 12,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'Brownian diffusion Smoluchowski method', selected: false },
        { label: 'CVODE', selected: false },
        { label: 'CVODES', selected: false },
        { label: 'Euler forward method', selected: false },
        { label: 'flux balance analysis', selected: false },
        { label: 'LSODA', selected: false },
        { label: 'LSODA/LSODAR hybrid method', selected: false },
        { label: 'NFSim agent-based simulation method', selected: false },
        { label: 'Resource Balance Analysis', selected: false },
        { label: 'synchronous logical model simulation method', selected: false },
      ],
    },
  },
  {
    id: 'simulator',
    key: ['simulationRun', 'simulatorName'],
    heading: 'Simulation tools',
    leftIcon: 'simulator',
    hidden: false,
    show: false,
    filterable: true,
    _index: 13,
    _visible: false,
    filterDefinition: {
      type: 'stringAutoComplete',
      value: [
        { label: 'AMICI 0.11.23', selected: false },
        { label: 'BioNetGen 2.7.0', selected: false },
        { label: 'BoolNet 2.1.5', selected: false },
        { label: 'COBRApy 0.22.1', selected: false },
        { label: 'COPASI 4.34.251', selected: false },
        { label: 'GINsim 3.0.0b', selected: false },
        { label: 'MASSpy 0.1.5', selected: false },
        { label: 'OpenCOR 2021-10-05', selected: false },
        { label: 'pyNeuroML 0.5.18', selected: false },
        { label: 'PySceS 1.0.0', selected: false },
        { label: 'RBApy 1.0.2', selected: false },
        { label: 'Smoldyn 2.67.2', selected: false },
        { label: 'tellurium 2.2.1', selected: false },
        { label: 'XPP 8.0', selected: false },
      ],
    },
  },
  {
    id: 'reports',
    key: 'outputs',
    heading: 'Reports',
    leftIcon: 'report',
    hidden: false,
    show: false,
    filterable: true,
    _index: 14,
    _visible: false,
    filterDefinition: { type: 'string', value: [{ label: 'Yes', selected: false }] },
  },
  {
    id: 'visualizations',
    key: 'outputs',
    heading: 'Visualizations',
    leftIcon: 'chart',
    hidden: false,
    show: false,
    filterable: true,
    _index: 15,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: '2D line plot', selected: false },
        { label: 'Vega', selected: false },
      ],
    },
  },
  {
    id: 'projectSize',
    key: ['simulationRun', 'projectSize'],
    heading: 'Project size',
    leftIcon: 'disk',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'number',
    units: 'MB',
    _index: 16,
    _visible: false,
    filterDefinition: { type: 'number', value: { min: 0, max: 8, step: 1, minSelected: 0, maxSelected: 8 } },
  },
  {
    id: 'cpus',
    key: ['simulationRun', 'cpus'],
    heading: 'CPUs',
    leftIcon: 'processor',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'number',
    _index: 17,
    _visible: false,
    filterDefinition: { type: 'number', value: { min: 1, max: 1, step: 1, minSelected: 1, maxSelected: 1 } },
  },
  {
    id: 'memory',
    key: ['simulationRun', 'memory'],
    heading: 'Memory',
    leftIcon: 'memory',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'number',
    units: 'GB',
    _index: 18,
    _visible: false,
    filterDefinition: { type: 'number', value: { min: 8, max: 8, step: 1, minSelected: 8, maxSelected: 8 } },
  },
  {
    id: 'resultsSize',
    key: ['simulationRun', 'resultsSize'],
    heading: 'Results size',
    leftIcon: 'disk',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'number',
    units: 'MB',
    _index: 19,
    _visible: false,
    filterDefinition: { type: 'number', value: { min: 0, max: 3, step: 1, minSelected: 0, maxSelected: 3 } },
  },
  {
    id: 'runtime',
    key: ['simulationRun', 'runtime'],
    heading: 'Runtime',
    leftIcon: 'duration',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'number',
    units: 'min',
    _index: 20,
    _visible: false,
    filterDefinition: { type: 'number', value: { min: 0, max: 4, step: 1, minSelected: 0, maxSelected: 4 } },
  },
  {
    id: 'simulationProvenance',
    key: ['metadata', 'locationPredecessors'],
    heading: 'Simulation provenance',
    leftIcon: 'backward',
    hidden: false,
    show: false,
    filterable: true,
    _index: 21,
    _visible: false,
    filterDefinition: { type: 'string', value: [{ label: 'Other', selected: false }] },
  },
  {
    id: 'organizations',
    key: ['owner', 'organizations'],
    heading: 'Organizations',
    leftIcon: 'organization',
    filterable: true,
    hidden: false,
    show: false,
    _index: 22,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'BioSimulations', selected: false },
        { label: 'ModelDB', selected: false },
      ],
    },
  },
  {
    id: 'owner',
    key: 'owner',
    heading: 'Owner',
    leftIcon: 'author',
    filterable: true,
    hidden: false,
    show: false,
    filterType: 'stringAutoComplete',
    _index: 23,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'Bilal Shaikh', selected: false },
        { label: 'BioSimulations', selected: false },
        { label: 'ModelDB', selected: false },
      ],
    },
  },
  {
    id: 'creators',
    key: ['metadata', 'creators'],
    heading: 'Creators',
    leftIcon: 'author',
    filterable: true,
    hidden: false,
    show: false,
    filterType: 'stringAutoComplete',
    _index: 24,
    _visible: false,
    filterDefinition: {
      type: 'stringAutoComplete',
      value: [
        { label: 'Aarash Bordbar', selected: false },
        { label: 'Alan Garny', selected: false },
        { label: "Alberto d'Onofrio", selected: false },
        { label: 'Ana Bulović', selected: false },
        { label: 'Andrea Ciliberto', selected: false },
        { label: 'Andreas Dräger', selected: false },
        { label: 'Anne Goelzer', selected: false },
        { label: 'Anze Zupanic', selected: false },
        { label: 'Aurélien Naldi', selected: false },
        { label: 'Axel von Kamp', selected: false },
        { label: 'Azusa Takizawa', selected: false },
        { label: 'Bela Novak', selected: false },
        { label: 'Benjamin Wicks', selected: false },
        { label: 'Bernhard O.Palsson', selected: false },
        { label: 'Bryan Kowal', selected: false },
        { label: 'Christian Poirier', selected: false },
        { label: 'Claudine Chaouiya', selected: false },
        { label: 'COBRApy Team', selected: false },
        { label: 'D. J. Irons', selected: false },
        { label: 'Daniel Bertrand', selected: false },
        { label: 'Daniel C. Zielinski', selected: false },
        { label: 'Daryl P. Shanley', selected: false },
        { label: 'David W. P. Dolan', selected: false },
        { label: 'Denis Thieffry', selected: false },
        { label: 'Douglas McCloskey', selected: false },
        { label: 'Duncan Bérenguier', selected: false },
        { label: 'Edda Klipp', selected: false },
        { label: 'Emanuel Gonçalves', selected: false },
        { label: 'Eric Henry', selected: false },
        { label: 'Felipe Golib', selected: false },
        { label: 'Finja Büchel', selected: false },
        { label: 'Futoshi Shibasaki', selected: false },
        { label: 'Giulio Caravagna', selected: false },
        { label: 'Glyn Nelson', selected: false },
        { label: 'Grey Davis', selected: false },
        { label: 'Han-Dong Chang', selected: false },
        { label: 'Hidde de Jong', selected: false },
        { label: 'Hope Shevchuk', selected: false },
        { label: 'Ioannis Xenarios', selected: false },
        { label: 'Jean-Pierre Changeux', selected: false },
        { label: 'Jignesh H Parmar', selected: false },
        { label: 'Jiun-Shian Wu', selected: false },
        { label: 'John J. Tyson', selected: false },
        { label: 'Julien Dorier', selected: false },
        { label: 'Julio Saez-Rodriguez', selected: false },
        { label: 'Kenzo Hirose', selected: false },
        { label: 'Lan K Nguyen', selected: false },
        { label: 'Laurent Tournier', selected: false },
        { label: 'Maciej Zylicz', selected: false },
        { label: 'Marc Dinh', selected: false },
        { label: 'Martijn P van Iersel', selected: false },
        { label: 'Masamitsu Iino', selected: false },
        { label: 'Michael Elowitz', selected: false },
        { label: 'Michael Hucka', selected: false },
        { label: 'Michel Page', selected: false },
        { label: 'Neema Jamshidi', selected: false },
        { label: 'Nicolas Le Novère', selected: false },
        { label: 'Nicolas Rodriguez', selected: false },
        { label: 'Nikolaus Sonnenschein', selected: false },
        { label: 'Olivier Schaad', selected: false },
        { label: 'Padraig Gleeson', selected: false },
        { label: 'Paolo Milazzo', selected: false },
        { label: 'Pedro Mendes', selected: false },
        { label: 'Pedro T Monteiro', selected: false },
        { label: 'Philip Hall', selected: false },
        { label: 'Roberto Barbuti', selected: false },
        { label: 'Sarah M Keating', selected: false },
        { label: 'Satomi Miwa', selected: false },
        { label: 'Sheng-Nan Wu', selected: false },
        { label: 'Stanislas Leibler', selected: false },
        { label: 'Steffen Klamt', selected: false },
        { label: 'Stephan Fischer', selected: false },
        { label: 'Steven Andrews', selected: false },
        { label: 'Stuart J. Edelstein', selected: false },
        { label: 'Taichiro Tomida', selected: false },
        { label: 'Thawfeek M Varusai', selected: false },
        { label: 'Thomas B. L. Kirkwood', selected: false },
        { label: 'Thomas Cokelaer', selected: false },
        { label: 'Tomáš Helikar', selected: false },
        { label: 'Vincent Fromion', selected: false },
        { label: 'Wolfram Liebermeister', selected: false },
        { label: 'Zuzanna Szymańska', selected: false },
      ],
    },
  },
  {
    id: 'contributors',
    key: ['metadata', 'contributors'],
    heading: 'Contributors',
    leftIcon: 'curator',
    filterable: true,
    hidden: false,
    show: false,
    filterType: 'stringAutoComplete',
    _index: 25,
    _visible: false,
    filterDefinition: {
      type: 'stringAutoComplete',
      value: [
        { label: 'Adrien Fauré', selected: false },
        { label: 'Claudine Chaouiya', selected: false },
        { label: 'Dougal Cowan', selected: false },
        { label: 'Harish Dharuri', selected: false },
        { label: 'James Faeder', selected: false },
        { label: 'Jeelean Lim', selected: false },
        { label: 'Johannes Meyer', selected: false },
        { label: 'Jonathan Karr', selected: false },
        { label: 'Jonathan R. Karr', selected: false },
        { label: 'Krishna Kumar Tiwari', selected: false },
        { label: 'Lukas Endler', selected: false },
        { label: 'Mohammad Umer Sharif Shohan', selected: false },
        { label: 'Moritz E. Beber', selected: false },
        { label: 'Nicolas Le Novère', selected: false },
        { label: 'Ryann Jordan', selected: false },
        { label: 'Sense Lab at Yale University', selected: false },
        { label: 'SenseLab', selected: false },
        { label: 'Thomas Cokelaer', selected: false },
        { label: 'Vijayalakshmi Chelliah', selected: false },
        { label: 'Zachary Haiman', selected: false },
      ],
    },
  },
  {
    id: 'funders',
    key: ['metadata', 'funders'],
    heading: 'Funders',
    leftIcon: 'funding',
    filterable: true,
    hidden: false,
    show: false,
    _index: 26,
    _visible: false,
    filterDefinition: { type: 'string', value: [] },
  },
  {
    id: 'license',
    key: ['metadata', 'license'],
    heading: 'License',
    leftIcon: 'license',
    filterable: true,
    hidden: false,
    show: false,
    _index: 27,
    _visible: false,
    filterDefinition: {
      type: 'string',
      value: [
        { label: 'CC0-1.0', selected: false },
        { label: 'GPL-2.0', selected: false },
        { label: 'GPL-3.0-only', selected: false },
        { label: 'GPL-3.0-or-later', selected: false },
        { label: 'LGPL-3.0-only', selected: false },
        { label: 'MIT', selected: false },
      ],
    },
  },
  {
    id: 'created',
    key: ['metadata', 'created'],
    heading: 'Created',
    leftIcon: 'date',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'date',
    _index: 28,
    _visible: false,
    filterDefinition: { type: 'date', value: { start: null, end: null } },
  },
  {
    id: 'published',
    key: 'created',
    heading: 'Published',
    leftIcon: 'date',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'date',
    _index: 29,
    _visible: false,
    filterDefinition: { type: 'date', value: { start: null, end: null } },
  },
  {
    id: 'updated',
    key: 'updated',
    heading: 'Updated',
    leftIcon: 'date',
    hidden: false,
    show: false,
    filterable: true,
    filterType: 'date',
    _index: 30,
    _visible: false,
    filterDefinition: { type: 'date', value: { start: null, end: null } },
  },
];
