#!/usr/bin/env bash
while read line
do
for app in $line; do
    __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    echo Testing $app
    source ${__dir}/docker-build -a $app 
done 
    
done < "${1:-/dev/stdin}"