#!/usr/bin/env bash
COMMIT=$(git rev-parse HEAD)
:"${DOCKER_BUILD_CONTEXT=..}" "${DOCKER_BACKEND_PATH=../Dockerfile}" "${TAG:=$COMMIT}" "${APP:=simulators-api}"

DOCKER_PATH=$DOCKER_BACKEND_PATH
DOCKER_HOST=docker.io
DOCKER_NAMESPACE=biosimulations

USAGE="$0 [-a <App Name> -t <Tag Name>]"

 while getopts 'a:t:' opt
 do
     case $opt in
         a) APP=$OPTARG;;
         t) TAG=$OPTARG;;
        \?) echo "ERROR: Invalid option: $USAGE"
            exit 1;;
     esac
done



DOCKER_IMAGE=$DOCKER_HOST/$DOCKER_NAMESPACE/$APP:$TAG
echo "Building $DOCKER_IMAGE"
docker build -f $DOCKER_PATH -t $DOCKER_IMAGE --build-arg app=$APP $DOCKER_BUILD_CONTEXT
