/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ACLS } from './aCLS';
import { InlineResponse20018Hrefs } from './inlineResponse20018Hrefs';

/**
 * TODO
 */
export interface InlineResponse20018 {
  acls?: ACLS;
  hrefs?: Array<InlineResponse20018Hrefs>;
}
