/**
 * BioSimulations Data Service
 * RESTful application programming interface documentation for the Biosimulations Data Service, based on the HDF Scalable Data Service (HSDS) from the HDF Group.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@biosimulations.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2008Hrefs } from './inlineResponse2008Hrefs';

/**
 * (See `GET /datasets/{id}`)
 */
export interface InlineResponse2008 {
  created?: number;
  lastModified?: number;
  shape?: object;
  /**
   * Must include references to only: `owner`, `root`, `self`.
   */
  hrefs?: Array<InlineResponse2008Hrefs>;
}
