#!/usr/bin/env python3

import argparse
import json
import os
import requests
import requests.adapters
import requests.exceptions
import simplejson.errors
import urllib3.util.retry

EXAMPLE_SIMULATIONS_RUNS_FILENAME = os.path.join(os.path.dirname(__file__),
                                                 '..', 'apps', 'dispatch', 'src', 'app', 'components',
                                                 'simulations', 'browse', 'example-simulations.{}.json')


def get_validate_endpoint(biosimulations_api, run_id, validate_simulation_results_data=True):
    """ Get the endpoint for checking the status of a simulation run

    Args:
        biosimulations_api (:obj:`str`): API to use to check the status of each run
            (``dev``, ``org``, or ``local``)
        run_id (:obj:`str`): id of the simulation run
        validate_simulation_results_data (:obj:`bool`, optional): whether to validate
            the data of the simulation results

    Returns:
        :obj:`str`: endpoint for checking the status of each simulation run
    """
    if biosimulations_api == 'local':
        endpoint = 'http://localhost:3333'
    else:
        endpoint = 'https://api.biosimulations.{}'.format(biosimulations_api)

    endpoint += '/runs/{}/validate'.format(run_id)

    if validate_simulation_results_data:
        endpoint += "?validateSimulationResultsData=true"

    return endpoint


def get_run_url(biosimulations_api, id):
    """ Get the URL for a simulation run

    Args:
        biosimulations_api (:obj:`str`): API to use to check the status of each run
            (``dev``, ``org``, or ``local``)

    Returns:
        :obj:`str`: URL for a simulation run
    """
    if biosimulations_api == 'local':
        return 'http://localhost:3333/simulations/{}'.format(id)

    return 'https://biosimulations.{}/simulations/{}'.format(biosimulations_api, id)


def get_failed_runs(examples_api, biosimulations_api, validate_simulation_results_data=True):
    """ Get a list of any example simulation runs that didn't succeed

    Args:
        examples_api (:obj:`str`): example set to test (``dev`` or ``org``)
        biosimulations_api (:obj:`str`): API to use to check the status of each run
            (``dev``, ``org``, or ``local``)
        validate_simulation_results_data (:obj:`bool`, optional): whether to validate
            the data of the simulation results

    Returns:
        :obj:`list` of :obj:`str`: ids and names of failed simulation runs
    """

    # get name of file with runs
    filename = EXAMPLE_SIMULATIONS_RUNS_FILENAME.format(examples_api)

    # read simulation runs
    with open(filename, 'r') as file:
        runs = json.load(file)

    # check the status of each run
    failures = []
    for run in runs:
        validate_endpoint = get_validate_endpoint(biosimulations_api, run['id'])
        response = requests.get(validate_endpoint)
        try:
            response.raise_for_status()
        except requests.exceptions.RequestException:
            try:
                error = response.json()['error'][0]['detail']
            except simplejson.errors.JSONDecodeError:
                error = 'Valiation failed'

            failures.append('<details><summary><b>{} (<a href="{}" target="_blank">{}</a>)</b></summary><br/>\n{}\n</details>'.format(
                run['name'], get_run_url(biosimulations_api, run['id']), run['id'], error,
            ))

    # return list of failed runs
    return failures


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Check that all of the example simulation runs succeeded.'
    )
    parser.add_argument(
        '--runbiosimulations-api',
        type=str,
        default='dev',
        help='BioSimulations API which for projects should be checked (`dev`, `org`, `local`). Default: `dev`.'
    )
    args = parser.parse_args()

    examples_api = args.runbiosimulations_api
    if examples_api == 'local':
        examples_api = 'dev'
    failures = get_failed_runs(examples_api, args.runbiosimulations_api)

    if failures:
        msg = 'The following example simulation runs did not succeed:\n\n{}'.format('\n\n'.join(failures))
        raise SystemExit(msg)
    else:
        print('All example simulation runs succeeded!')
