name: Update COMBINE API client

on:
  push:
    paths:
      - 'apps/combine-api/combine_api/spec/spec.yml'
  workflow_dispatch:
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  buildClient:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          sudo apt-get -y install perl

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '18'

      - name: Print node and npm versions
        run: |
          node --version
          npm --version

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Install nx CLI
        run: npm install -g @nx

      - name: Build Nest client
        run: tools/generate-combine-api-nest-client

      - name: Build Angular client
        run: tools/generate-combine-api-angular-client

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8.0.2
        with:
          add: "['libs/combine-api/nest-client/src/lib/api/', 'libs/combine-api/nest-client/src/lib/model/', 'libs/combine-api/nest-angular/src/lib/api/', 'libs/combine-api/nest-angular/src/lib/model/']"
          message: 'refactor(combine-api): update clients'
          author_name: BioSimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          commit: --signoff
          pull: '--rebase --autostash'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged
